### ISSUE TITLE
unwatch

### ISSUE THREAD

**Issue by rmalina** [cassininazir/creativedisturbance#117]
i have heard people complain about the stream of notifications from github
can you inform everyone how to change their settings on github so they a
are only notified re github tasks they are involved in

roger

**Comment by cassininazir** [comment]
Sent email. Including content here for future reference.

Wanted to share with you how you may “unwatch” GitHub tasks and thereby clear up your inbox.

You can change your notifcation settings by logging into your account and going to github.com/settings/notifications and may unwatch (1) specific tasks and (2) repositories. 

1. To unwatch a task (and disable email notifications for that task):
Open the task in a web browser
Select Unwatch (see screenshot below for location)
And make a selection: not watching, watching, ignoring. 

![screen shot 2015-03-09 at 3 23 57 pm](https://cloud.githubusercontent.com/assets/1661430/6564643/84be5268-c678-11e4-9f3d-8a51a3c3378c.png)

2. To unwatch a repo, see the article below. Be careful doing this, because you will not get notified of any new tasks in that repo. 
 help.github.com/articles/unwatching-repositories
